# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gerrit/Documents/Projects/PureSU3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gerrit/Documents/Projects/PureSU3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gerrit/Documents/Projects/PureSU3/CMakeFiles /home/gerrit/Documents/Projects/PureSU3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gerrit/Documents/Projects/PureSU3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PureSU3

# Build rule for target.
PureSU3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PureSU3
.PHONY : PureSU3

# fast build rule for target.
PureSU3/fast:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/build
.PHONY : PureSU3/fast

src/LatticeSettings.o: src/LatticeSettings.cpp.o

.PHONY : src/LatticeSettings.o

# target to build an object file
src/LatticeSettings.cpp.o:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/LatticeSettings.cpp.o
.PHONY : src/LatticeSettings.cpp.o

src/LatticeSettings.i: src/LatticeSettings.cpp.i

.PHONY : src/LatticeSettings.i

# target to preprocess a source file
src/LatticeSettings.cpp.i:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/LatticeSettings.cpp.i
.PHONY : src/LatticeSettings.cpp.i

src/LatticeSettings.s: src/LatticeSettings.cpp.s

.PHONY : src/LatticeSettings.s

# target to generate assembly for a file
src/LatticeSettings.cpp.s:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/LatticeSettings.cpp.s
.PHONY : src/LatticeSettings.cpp.s

src/Matrix.o: src/Matrix.cpp.o

.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i

.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s

.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/Random.o: src/Random.cpp.o

.PHONY : src/Random.o

# target to build an object file
src/Random.cpp.o:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Random.cpp.o
.PHONY : src/Random.cpp.o

src/Random.i: src/Random.cpp.i

.PHONY : src/Random.i

# target to preprocess a source file
src/Random.cpp.i:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Random.cpp.i
.PHONY : src/Random.cpp.i

src/Random.s: src/Random.cpp.s

.PHONY : src/Random.s

# target to generate assembly for a file
src/Random.cpp.s:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Random.cpp.s
.PHONY : src/Random.cpp.s

src/SUNLattice.o: src/SUNLattice.cpp.o

.PHONY : src/SUNLattice.o

# target to build an object file
src/SUNLattice.cpp.o:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/SUNLattice.cpp.o
.PHONY : src/SUNLattice.cpp.o

src/SUNLattice.i: src/SUNLattice.cpp.i

.PHONY : src/SUNLattice.i

# target to preprocess a source file
src/SUNLattice.cpp.i:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/SUNLattice.cpp.i
.PHONY : src/SUNLattice.cpp.i

src/SUNLattice.s: src/SUNLattice.cpp.s

.PHONY : src/SUNLattice.s

# target to generate assembly for a file
src/SUNLattice.cpp.s:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/SUNLattice.cpp.s
.PHONY : src/SUNLattice.cpp.s

src/TwoLinkOperator.o: src/TwoLinkOperator.cpp.o

.PHONY : src/TwoLinkOperator.o

# target to build an object file
src/TwoLinkOperator.cpp.o:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/TwoLinkOperator.cpp.o
.PHONY : src/TwoLinkOperator.cpp.o

src/TwoLinkOperator.i: src/TwoLinkOperator.cpp.i

.PHONY : src/TwoLinkOperator.i

# target to preprocess a source file
src/TwoLinkOperator.cpp.i:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/TwoLinkOperator.cpp.i
.PHONY : src/TwoLinkOperator.cpp.i

src/TwoLinkOperator.s: src/TwoLinkOperator.cpp.s

.PHONY : src/TwoLinkOperator.s

# target to generate assembly for a file
src/TwoLinkOperator.cpp.s:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/TwoLinkOperator.cpp.s
.PHONY : src/TwoLinkOperator.cpp.s

src/Vectors.o: src/Vectors.cpp.o

.PHONY : src/Vectors.o

# target to build an object file
src/Vectors.cpp.o:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Vectors.cpp.o
.PHONY : src/Vectors.cpp.o

src/Vectors.i: src/Vectors.cpp.i

.PHONY : src/Vectors.i

# target to preprocess a source file
src/Vectors.cpp.i:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Vectors.cpp.i
.PHONY : src/Vectors.cpp.i

src/Vectors.s: src/Vectors.cpp.s

.PHONY : src/Vectors.s

# target to generate assembly for a file
src/Vectors.cpp.s:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/Vectors.cpp.s
.PHONY : src/Vectors.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PureSU3.dir/build.make CMakeFiles/PureSU3.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PureSU3"
	@echo "... src/LatticeSettings.o"
	@echo "... src/LatticeSettings.i"
	@echo "... src/LatticeSettings.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/Random.o"
	@echo "... src/Random.i"
	@echo "... src/Random.s"
	@echo "... src/SUNLattice.o"
	@echo "... src/SUNLattice.i"
	@echo "... src/SUNLattice.s"
	@echo "... src/TwoLinkOperator.o"
	@echo "... src/TwoLinkOperator.i"
	@echo "... src/TwoLinkOperator.s"
	@echo "... src/Vectors.o"
	@echo "... src/Vectors.i"
	@echo "... src/Vectors.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

